# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :build_and_upload_symbols do
    gym(
      workspace: 'AltRant.xcworkspace',
      scheme: 'AltRant',
      clean: false,
      export_method: 'development',
      catalyst_platform: 'macos',
      skip_archive: true,
    )

    sentry_upload_dsym(
      auth_token: '914d357930ae44b7a48e68406fe5b3372779ce79273d458aaa2c437bcc61f057',
      org_slug: 'crack-software',
      project_slug: 'crack-software',
      dsym_path: 'AltRant.app.dSYM.zip',
    )
  end

  lane :run_on_ios do
    install_on_device(
      ipa: './AltRant.ipa',
      extra: '--justlaunch',
    )
  end
end
